### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by rawnly** [jrmoulton/tmux-sessionizer#15]
Maybe it's my fault due to misconfiguration but when i run `tms` it's stuck without showing results.

[video demo](https://share.cleanshot.com/NfQB9H9b)

heres' my config: 

```toml
search_paths = ['/Users/federicovitale/Developer']
excluded_dirs = ['/Users/federicovitale/Developer/PYTHON']
default_session = 'wez-main'
```
